version: '3.8'

services:
  db:
    container_name: redd-dyra-db
    # image: postgres:14
    build: postgres
    restart: "no"
    environment:
      POSTGRES_DB: redd_dyra
      POSTGRES_PASSWORD: redd_alle_dyrene! # Local development password
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - 5432:5432